# Test for normalization vs standardization:


In [64]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## A. Test

In [65]:
from helpers import *
from implementations import *
SET_TRAIN = 'data/train.csv' # download train data
y, tx, ids = load_csv_data(SET_TRAIN)

In [66]:
tx, to_replace = data_processing(y, tx)

In [8]:
# a ajouter dans implementations

def normalize(x):
    """Normalize the original data set."""
    max_ = np.max(x, axis=0)
    min_ = np.min(x, axis=0)
    d = max_ - min_
    x = x - min_
    x = x/d
    return x, max_, min_



In [67]:
print(y.shape)
print(tx[:,0])
X0 = np.ones((tx.shape[0],1))
tx = np.hstack((X0, tx))
print(tx[:,0])

(250000,)
[0.57593058 0.67590611 0.44404925 ... 0.42902659 0.38227612 0.44404925]
[1. 1. 1. ... 1. 1. 1.]


In [68]:
#initial_w = least_squares(y, tx)[0]

In [69]:
print(initial_w)

[-0.08949664 -0.08949664 -0.02839191 -0.06330538 -0.02881592 -0.00523081
  0.00636063 -0.05868574 -0.03449468 -0.01422326 -0.0084115  -0.01023227
  0.01379633  0.00616091 -0.04403773 -0.04484701 -0.01713457 -0.04355938
 -0.04445558 -0.02545906 -0.04312265 -0.0299993  -0.0080909  -0.04445076
 -0.04452728 -0.00059747]


In [74]:
# Define the parameters of the algorithm.
max_iters = 1000
gamma = 0.1

In [75]:
initial_w = np.zeros(tx.shape[1])

In [76]:
y[ y == -1 ] = 0
print(y)

[1. 0. 0. ... 1. 0. 0.]


In [77]:
lr_w, lr_loss = logistic_regression(y, tx, initial_w, max_iters, gamma)
print(lr_loss)

Current iteration=0, loss=0.6831821519904668
Current iteration=100, loss=0.5968155797168668
Current iteration=200, loss=0.570157976941008
Current iteration=300, loss=0.5523022768844897
Current iteration=400, loss=0.5383722500330579
Current iteration=500, loss=0.5267996662365861
Current iteration=600, loss=0.5169085041569688
Current iteration=700, loss=0.5083197472840506
Current iteration=800, loss=0.5007810976742949
Current iteration=900, loss=0.4941084012099184
0.48821687000827935


In [78]:
initial_w = lr_w

In [79]:
gamma = 0.01
lr_w, lr_loss = logistic_regression(y, tx, initial_w, max_iters, gamma)

Current iteration=0, loss=0.4882112411258915
Current iteration=100, loss=0.4876514293705867
Current iteration=200, loss=0.4870976446253641
Current iteration=300, loss=0.48654979138517845
Current iteration=400, loss=0.4860077761769963
Current iteration=500, loss=0.4854715075033281
Current iteration=600, loss=0.4849408957878136
Current iteration=700, loss=0.48441585332276277
Current iteration=800, loss=0.48389629421856
Current iteration=900, loss=0.4833821343548463


In [80]:
initial_w = lr_w

In [81]:
gamma = 0.001
lr_w, lr_loss = logistic_regression(y, tx, initial_w, max_iters, gamma)

Current iteration=0, loss=0.4828778474620509
Current iteration=100, loss=0.482827248931626
Current iteration=200, loss=0.48277670268514544
Current iteration=300, loss=0.48272620864295374
Current iteration=400, loss=0.48267576672555823
Current iteration=500, loss=0.48262537685362733
Current iteration=600, loss=0.48257503894799236
Current iteration=700, loss=0.48252475292964453
Current iteration=800, loss=0.482474518719736
Current iteration=900, loss=0.48242433623957975


In [85]:
lambdas = np.logspace(-3, 0, 5)
print(lambdas)

#for ind, lambda_ in enumerate(lambdas):
   # rlr_w, rlr_loss = reg_logistic_regression(y, tx, lambda_, initial_w, max_iters, gamma)


[0.001      0.00562341 0.03162278 0.17782794 1.        ]
